[2023-12-22T19:02:36.289+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: batch_layer.income_statement manual__2023-12-22T18:57:29.934656+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
