[2023-12-23T12:06:56.456+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: batch_layer.batch_0 manual__2023-12-23T12:02:27.039594+00:00 [queued]>
[2023-12-23T12:06:56.461+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: batch_layer.batch_0 manual__2023-12-23T12:02:27.039594+00:00 [queued]>
[2023-12-23T12:06:56.462+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2023-12-23T12:06:56.475+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): batch_0> on 2023-12-23 12:02:27.039594+00:00
[2023-12-23T12:06:56.479+0000] {standard_task_runner.py:60} INFO - Started process 931 to run task
[2023-12-23T12:06:56.482+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'batch_layer', 'batch_0', 'manual__2023-12-23T12:02:27.039594+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/BatchLayerDag.py', '--cfg-path', '/tmp/tmp5ropmt2u']
[2023-12-23T12:06:56.484+0000] {standard_task_runner.py:88} INFO - Job 16: Subtask batch_0
[2023-12-23T12:06:56.511+0000] {task_command.py:423} INFO - Running <TaskInstance: batch_layer.batch_0 manual__2023-12-23T12:02:27.039594+00:00 [running]> on host 7de9f6b6c8f6
[2023-12-23T12:06:56.557+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='airflow@example.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='batch_layer' AIRFLOW_CTX_TASK_ID='batch_0' AIRFLOW_CTX_EXECUTION_DATE='2023-12-23T12:02:27.039594+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-23T12:02:27.039594+00:00'
[2023-12-23T12:06:56.609+0000] {hive.py:475} INFO - USE `finnhub_db`
[2023-12-23T12:06:56.644+0000] {hive.py:475} INFO - 
                SELECT *
                FROM finnhub_table
            
[2023-12-23T12:06:58.349+0000] {logging_mixin.py:188} INFO -           date  hour           s         sum_v
0   2023-12-17    21     BINANCE  1.299586e+02
1   2023-12-20    19        AAPL  8.818790e+05
2   2023-12-20    19        AMZN  1.265163e+06
3   2023-12-20    19  IC MARKETS  0.000000e+00
4   2023-12-21    21        AAPL  1.960000e+02
5   2023-12-21    21        AMZN  1.400000e+01
6   2023-12-21    21     BINANCE  3.741818e+02
7   2023-12-22    15        AAPL  3.264000e+03
8   2023-12-22    15        AMZN  1.188000e+03
9   2023-12-22    15     BINANCE  6.588000e-02
10  2023-12-22    15        MSFT  1.476000e+03
11  2023-12-22    20        AAPL  5.074800e+04
12  2023-12-22    20        AMZN  4.971600e+04
13  2023-12-22    20     BINANCE  1.028364e+01
14  2023-12-22    20        MSFT  2.900400e+04
15  2023-12-22    21        AAPL  2.936200e+04
16  2023-12-22    21        AMZN  4.490000e+02
17  2023-12-22    21     BINANCE  1.183529e+03
18  2023-12-22    23        AAPL  1.067000e+03
19  2023-12-22    23        AMZN  6.200000e+01
20  2023-12-22    23     BINANCE  1.345824e+02
21  2023-12-22    23        MSFT  1.000000e+02
22  2023-12-23    11     BINANCE  4.587726e+01
[2023-12-23T12:06:58.450+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/BatchLayerDag.py", line 21, in batch_0
    b0.batch_proc_0()
  File "/opt/airflow/dags/batch_proc_0.py", line 64, in batch_proc_0
    transformed_data = transform_data(df.copy())
  File "/opt/airflow/dags/batch_proc_0.py", line 13, in transform_data
    df_resampled = df.resample('H').sum()
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/resample.py", line 888, in sum
    return self._downsample("sum", numeric_only=numeric_only, min_count=min_count)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/resample.py", line 1297, in _downsample
    result = obj.groupby(self.grouper, axis=self.axis).aggregate(how, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/groupby/generic.py", line 1269, in aggregate
    result = op.agg()
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/apply.py", line 160, in agg
    return self.apply_str()
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/apply.py", line 496, in apply_str
    return self._try_aggregate_string_function(obj, f, *self.args, **self.kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/apply.py", line 565, in _try_aggregate_string_function
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/groupby/groupby.py", line 2263, in sum
    result = self._agg_general(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/groupby/groupby.py", line 1422, in _agg_general
    result = self._cython_agg_general(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/groupby/groupby.py", line 1507, in _cython_agg_general
    new_mgr = data.grouped_reduce(array_func)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 1503, in grouped_reduce
    applied = sb.apply(func)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/blocks.py", line 329, in apply
    result = func(self.values, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/groupby/groupby.py", line 1490, in array_func
    result = self.grouper._cython_operation(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/groupby/ops.py", line 959, in _cython_operation
    return cy_op.cython_operation(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/groupby/ops.py", line 657, in cython_operation
    return self._cython_op_ndim_compat(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/groupby/ops.py", line 497, in _cython_op_ndim_compat
    return self._call_cython_op(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/groupby/ops.py", line 549, in _call_cython_op
    func(
  File "pandas/_libs/groupby.pyx", line 717, in pandas._libs.groupby.group_sum
TypeError: unsupported operand type(s) for +: 'datetime.date' and 'datetime.date'
[2023-12-23T12:06:58.468+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=batch_layer, task_id=batch_0, execution_date=20231223T120227, start_date=20231223T120656, end_date=20231223T120658
[2023-12-23T12:06:58.481+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 16 for task batch_0 (unsupported operand type(s) for +: 'datetime.date' and 'datetime.date'; 931)
[2023-12-23T12:06:58.502+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2023-12-23T12:06:58.510+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
