[2023-12-26T00:06:05.236+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: serving-layer.serving scheduled__2023-12-25T00:00:00+00:00 [queued]>
[2023-12-26T00:06:05.241+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: serving-layer.serving scheduled__2023-12-25T00:00:00+00:00 [queued]>
[2023-12-26T00:06:05.242+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2023-12-26T00:06:05.254+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): serving> on 2023-12-25 00:00:00+00:00
[2023-12-26T00:06:05.259+0000] {standard_task_runner.py:60} INFO - Started process 2897 to run task
[2023-12-26T00:06:05.261+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'serving-layer', 'serving', 'scheduled__2023-12-25T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/servingLayer.py', '--cfg-path', '/tmp/tmpm07dt1nj']
[2023-12-26T00:06:05.263+0000] {standard_task_runner.py:88} INFO - Job 14: Subtask serving
[2023-12-26T00:06:05.289+0000] {task_command.py:423} INFO - Running <TaskInstance: serving-layer.serving scheduled__2023-12-25T00:00:00+00:00 [running]> on host 5e983ae2bbe8
[2023-12-26T00:06:05.544+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='airflow@example.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='serving-layer' AIRFLOW_CTX_TASK_ID='serving' AIRFLOW_CTX_EXECUTION_DATE='2023-12-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-25T00:00:00+00:00'
[2023-12-26T00:06:13.596+0000] {logging_mixin.py:188} INFO - Error: could not translate host name "postgres" to address: Temporary failure in name resolution
[2023-12-26T00:06:13.597+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/servingLayer.py", line 79, in process_parquet_files
    if cursor:
UnboundLocalError: local variable 'cursor' referenced before assignment
[2023-12-26T00:06:13.613+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=serving-layer, task_id=serving, execution_date=20231225T000000, start_date=20231226T000605, end_date=20231226T000613
[2023-12-26T00:06:13.623+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 14 for task serving (local variable 'cursor' referenced before assignment; 2897)
[2023-12-26T00:06:13.651+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2023-12-26T00:06:13.659+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-12-26T12:45:49.794+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: serving-layer.serving scheduled__2023-12-25T00:00:00+00:00 [queued]>
[2023-12-26T12:45:49.800+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: serving-layer.serving scheduled__2023-12-25T00:00:00+00:00 [queued]>
[2023-12-26T12:45:49.800+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2023-12-26T12:45:49.814+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): serving> on 2023-12-25 00:00:00+00:00
[2023-12-26T12:45:49.818+0000] {standard_task_runner.py:60} INFO - Started process 191 to run task
[2023-12-26T12:45:49.821+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'serving-layer', 'serving', 'scheduled__2023-12-25T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/servingLayer.py', '--cfg-path', '/tmp/tmpxl2x3dlp']
[2023-12-26T12:45:49.823+0000] {standard_task_runner.py:88} INFO - Job 6: Subtask serving
[2023-12-26T12:45:49.855+0000] {task_command.py:423} INFO - Running <TaskInstance: serving-layer.serving scheduled__2023-12-25T00:00:00+00:00 [running]> on host 21f64a9239d6
[2023-12-26T12:45:50.018+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='airflow@example.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='serving-layer' AIRFLOW_CTX_TASK_ID='serving' AIRFLOW_CTX_EXECUTION_DATE='2023-12-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-25T00:00:00+00:00'
[2023-12-26T12:45:58.022+0000] {logging_mixin.py:188} INFO - Error: could not translate host name "postgres" to address: Temporary failure in name resolution
[2023-12-26T12:45:58.023+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/servingLayer.py", line 79, in process_parquet_files
    if cursor:
UnboundLocalError: local variable 'cursor' referenced before assignment
[2023-12-26T12:45:58.034+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=serving-layer, task_id=serving, execution_date=20231225T000000, start_date=20231226T124549, end_date=20231226T124558
[2023-12-26T12:45:58.057+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 6 for task serving (local variable 'cursor' referenced before assignment; 191)
[2023-12-26T12:45:58.087+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2023-12-26T12:45:58.098+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-12-26T16:40:34.079+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: serving-layer.serving scheduled__2023-12-25T00:00:00+00:00 [queued]>
[2023-12-26T16:40:34.084+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: serving-layer.serving scheduled__2023-12-25T00:00:00+00:00 [queued]>
[2023-12-26T16:40:34.084+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2023-12-26T16:40:34.096+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): serving> on 2023-12-25 00:00:00+00:00
[2023-12-26T16:40:34.099+0000] {standard_task_runner.py:60} INFO - Started process 191 to run task
[2023-12-26T16:40:34.101+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'serving-layer', 'serving', 'scheduled__2023-12-25T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/servingLayer.py', '--cfg-path', '/tmp/tmpuw7hthvv']
[2023-12-26T16:40:34.102+0000] {standard_task_runner.py:88} INFO - Job 6: Subtask serving
[2023-12-26T16:40:34.130+0000] {task_command.py:423} INFO - Running <TaskInstance: serving-layer.serving scheduled__2023-12-25T00:00:00+00:00 [running]> on host ba237c0dfd1a
[2023-12-26T16:40:34.266+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='airflow@example.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='serving-layer' AIRFLOW_CTX_TASK_ID='serving' AIRFLOW_CTX_EXECUTION_DATE='2023-12-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-25T00:00:00+00:00'
[2023-12-26T16:40:42.270+0000] {logging_mixin.py:188} INFO - Error: could not translate host name "postgres" to address: Temporary failure in name resolution
[2023-12-26T16:40:42.272+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/servingLayer.py", line 79, in process_parquet_files
    if cursor:
UnboundLocalError: local variable 'cursor' referenced before assignment
[2023-12-26T16:40:42.283+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=serving-layer, task_id=serving, execution_date=20231225T000000, start_date=20231226T164034, end_date=20231226T164042
[2023-12-26T16:40:42.323+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 6 for task serving (local variable 'cursor' referenced before assignment; 191)
[2023-12-26T16:40:42.372+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2023-12-26T16:40:42.387+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-12-26T20:57:57.299+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: serving-layer.serving scheduled__2023-12-25T00:00:00+00:00 [queued]>
[2023-12-26T20:57:57.306+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: serving-layer.serving scheduled__2023-12-25T00:00:00+00:00 [queued]>
[2023-12-26T20:57:57.306+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2023-12-26T20:57:57.317+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): serving> on 2023-12-25 00:00:00+00:00
[2023-12-26T20:57:57.321+0000] {standard_task_runner.py:60} INFO - Started process 191 to run task
[2023-12-26T20:57:57.326+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'serving-layer', 'serving', 'scheduled__2023-12-25T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/servingLayer.py', '--cfg-path', '/tmp/tmpdy0_bmk0']
[2023-12-26T20:57:57.329+0000] {standard_task_runner.py:88} INFO - Job 6: Subtask serving
[2023-12-26T20:57:57.358+0000] {task_command.py:423} INFO - Running <TaskInstance: serving-layer.serving scheduled__2023-12-25T00:00:00+00:00 [running]> on host d26df5132269
[2023-12-26T20:57:57.520+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='airflow@example.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='serving-layer' AIRFLOW_CTX_TASK_ID='serving' AIRFLOW_CTX_EXECUTION_DATE='2023-12-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-25T00:00:00+00:00'
[2023-12-26T20:57:57.825+0000] {logging_mixin.py:188} INFO - Error: 'column1'
[2023-12-26T20:57:57.825+0000] {python.py:201} INFO - Done. Returned value was: None
[2023-12-26T20:57:57.829+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=serving-layer, task_id=serving, execution_date=20231225T000000, start_date=20231226T205757, end_date=20231226T205757
[2023-12-26T20:57:57.863+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2023-12-26T20:57:57.872+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-12-26T21:33:46.901+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: serving-layer.serving scheduled__2023-12-25T00:00:00+00:00 [queued]>
[2023-12-26T21:33:46.906+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: serving-layer.serving scheduled__2023-12-25T00:00:00+00:00 [queued]>
[2023-12-26T21:33:46.907+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2023-12-26T21:33:46.918+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): serving> on 2023-12-25 00:00:00+00:00
[2023-12-26T21:33:46.922+0000] {standard_task_runner.py:60} INFO - Started process 192 to run task
[2023-12-26T21:33:46.924+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'serving-layer', 'serving', 'scheduled__2023-12-25T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/servingLayer.py', '--cfg-path', '/tmp/tmpjab9s4z4']
[2023-12-26T21:33:46.926+0000] {standard_task_runner.py:88} INFO - Job 6: Subtask serving
[2023-12-26T21:33:46.953+0000] {task_command.py:423} INFO - Running <TaskInstance: serving-layer.serving scheduled__2023-12-25T00:00:00+00:00 [running]> on host b20a8cc54a2d
[2023-12-26T21:33:47.121+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='airflow@example.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='serving-layer' AIRFLOW_CTX_TASK_ID='serving' AIRFLOW_CTX_EXECUTION_DATE='2023-12-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-25T00:00:00+00:00'
[2023-12-26T21:33:47.387+0000] {logging_mixin.py:188} INFO - Error: 'column1'
[2023-12-26T21:33:47.388+0000] {python.py:201} INFO - Done. Returned value was: None
[2023-12-26T21:33:47.392+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=serving-layer, task_id=serving, execution_date=20231225T000000, start_date=20231226T213346, end_date=20231226T213347
[2023-12-26T21:33:47.418+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2023-12-26T21:33:47.427+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-12-26T22:20:32.594+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: serving-layer.serving scheduled__2023-12-25T00:00:00+00:00 [queued]>
[2023-12-26T22:20:32.605+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: serving-layer.serving scheduled__2023-12-25T00:00:00+00:00 [queued]>
[2023-12-26T22:20:32.606+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2023-12-26T22:20:32.629+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): serving> on 2023-12-25 00:00:00+00:00
[2023-12-26T22:20:32.635+0000] {standard_task_runner.py:60} INFO - Started process 187 to run task
[2023-12-26T22:20:32.637+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'serving-layer', 'serving', 'scheduled__2023-12-25T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/servingLayer.py', '--cfg-path', '/tmp/tmp2r5zx_6_']
[2023-12-26T22:20:32.639+0000] {standard_task_runner.py:88} INFO - Job 6: Subtask serving
[2023-12-26T22:20:32.666+0000] {task_command.py:423} INFO - Running <TaskInstance: serving-layer.serving scheduled__2023-12-25T00:00:00+00:00 [running]> on host f81c64188a37
[2023-12-26T22:20:32.832+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='airflow@example.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='serving-layer' AIRFLOW_CTX_TASK_ID='serving' AIRFLOW_CTX_EXECUTION_DATE='2023-12-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-25T00:00:00+00:00'
[2023-12-26T22:20:33.088+0000] {logging_mixin.py:188} INFO - Error: 'column1'
[2023-12-26T22:20:33.089+0000] {python.py:201} INFO - Done. Returned value was: None
[2023-12-26T22:20:33.093+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=serving-layer, task_id=serving, execution_date=20231225T000000, start_date=20231226T222032, end_date=20231226T222033
[2023-12-26T22:20:33.133+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2023-12-26T22:20:33.141+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
